version: "3.2"
services:
  qrcode:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      QR_CODE_IMAGE_DIRECTORY: 'images'
      QR_CODE_DEFAULT_URL: 'https://www.github.com/ge64'
      QR_CODE_DEFAULT_FILE_NAME: 'github.png'
    volumes:
      - .:/home/myuser